name: spotify-clone

services:
  cassandra:
    image: cassandra:5.0
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: SpotifyCluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 32
      MAX_HEAP_SIZE: 2G
      HEAP_NEWSIZE: 800M
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./scripts/init.cql:/init_files/init.cql:ro
    networks:
      - spotify-clone-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.1
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: dev-file
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./scripts/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command: start-dev --import-realm
    depends_on:
      - cassandra
    networks:
      - spotify-clone-network

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - spotify-clone-minio-object-storage:/data
      - ./scripts/initialize_minio.sh:/initialize.sh
    entrypoint: ["/bin/sh", "/initialize.sh"]
    networks:
      - spotify-clone-network

  stream-service:
    #image: ghcr.io/yarvannim/spotify-clone/stream-service:latest
    image: stream-service:local
    build:
      context: ./stream-service
      dockerfile: Dockerfile
    container_name: stream-service
    ports:
      - "8008:8008"
    environment:
      OBJECT_STORAGE_PROVIDER: ${PROVIDER}
      OBJECT_STORAGE_ENDPOINT: ${ENDPOINT}
      OBJECT_STORAGE_ACCESS_KEY: ${ACCESS_KEY}
      OBJECT_STORAGE_SECRET_KEY: ${SECRET_KEY}
      OBJECT_STORAGE_REGION: ${REGION}
      OBJECT_STORAGE_BUCKET_NAME: ${BUCKET_NAME}
      OBJECT_STORAGE_PRESIGNED_URL_EXPIRATION_MINUTES: ${PRESIGNED_URL_EXPIRATION_MINUTES}
    networks:
      - spotify-clone-network
    depends_on:
      - minio
      - cassandra
      - keycloak
    pull_policy: always

networks:
  spotify-clone-network:
    name: spotify-clone-network
    driver: bridge

volumes:
  spotify-clone-minio-object-storage:
    name: spotify-clone-minio-object-storage
  keycloak_data:
    name: keycloak_data
  cassandra_data:
    name: cassandra_data

