name: spotify-clone

services:
  vault:
    image: hashicorp/vault:1.21
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://vault:8200"
      VAULT_API_ADDR: "http://vault:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
    command: server -dev -dev-root-token-id="root-token"
    networks:
      - spotify-clone-network

  cassandra:
    image: cassandra:5.0
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: SpotifyCluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 32
      MAX_HEAP_SIZE: 2G
      HEAP_NEWSIZE: 800M
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./scripts/init.cql:/init_files/init.cql:ro
    networks:
      - spotify-clone-network

  elasticsearch:
    image: elasticsearch:8.17.10
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - spotify-clone-network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.1
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: dev-file
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./scripts/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command: start-dev --import-realm
    depends_on:
      - cassandra
    networks:
      - spotify-clone-network

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - spotify-clone-minio-object-storage:/data
      - ./scripts/initialize_minio.sh:/initialize.sh
    entrypoint: ["/bin/sh", "/initialize.sh"]
    networks:
      - spotify-clone-network

  stream-service:
    #image: ghcr.io/yarvannim/spotify-clone/stream-service:latest
    image: stream-service:local
    build:
      context: ./stream-service
      dockerfile: Dockerfile
    container_name: stream-service
    ports:
      - "8008:8008"
    environment:
      SPRING_CLOUD_VAULT_URI: http://vault:8200
      SPRING_CLOUD_VAULT_TOKEN: root-token

      OBJECT_STORAGE_PROVIDER: MINIO
      OBJECT_STORAGE_ENDPOINT: http://minio:9000
      OBJECT_STORAGE_REGION: eu-west-1
      OBJECT_STORAGE_BUCKET_NAME: music
      OBJECT_STORAGE_PRESIGNED_URL_EXPIRATION_MINUTES: 10
    networks:
      - spotify-clone-network
    depends_on:
      minio:
        condition: service_started
      cassandra:
        condition: service_started
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    pull_policy: always

  frontend:
    image: react-client:local
    build:
      context: ./react-client
      dockerfile: Dockerfile
    container_name: react-client
    ports:
      - "3000:80"
    networks:
      - spotify-clone-network
    depends_on:
      - stream-service
      - keycloak
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  spotify-clone-network:
    name: spotify-clone-network
    driver: bridge

volumes:
  spotify-clone-minio-object-storage:
    name: spotify-clone-minio-object-storage
  keycloak_data:
    name: keycloak_data
  cassandra_data:
    name: cassandra_data
  elasticsearch_data:
    name: elasticsearch_data
  vault_data:
    name: vault_data