name: Service CI

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      service-path:
        required: true
        type: string
      test-command:
        required: false
        type: string
        default: "echo 'No tests specified'"
      dockerfile-path:
        required: true
        type: string
        Default: "./Dockerfile"
      enable-test:
        required: false
        type: boolean
        default: true


jobs:
  service-ci:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: yarvannim/spotify-clone/${{ inputs.service-name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        if: github.ref == 'refs/heads/main' && success()
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.service-path }}
          file: ${{ inputs.service-path }}/${ inputs.dockerfile-path }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' || github.event_name == 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha,scope=${{ inputs.service-name }}
          cache-to: type=gha,scope=${{ inputs.service-name }},mode=max
          outputs: type=docker,dest=/tmp/${{ inputs.service-name }}.tar

      - name: Load Docker image for testing
        if: inputs.enable-test
        run: |
          docker load --input /tmp/${{ inputs.service-name }}.tar

      - name: Run tests
        if: inputs.enable-test
        run: |

      - name: Security scan
        if: github.ref == 'refs/heads/main' && success()
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          severity: critical,high

      - name: Trivy vulnerability scan
        if: github.ref == 'refs/heads/main' && success()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          format: sarif
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        if: github.ref == 'refs/heads/main' && success()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'